### ISSUE TITLE
服务调用报错：TypeError: _create_embedding() got an unexpected keyword argument 'model_config'

### ISSUE THREAD

**Issue by cy565025164** [limcheekin/open-text-embeddings#1] opened 2023-09-11 18:33 UTC

**Comment by limcheekin** [comment] 2023-09-27 09:55
The issue is fixed by a contributor [Vokturz](https://github.com/Vokturz) at [#2](https://github.com/limcheekin/open-text-embeddings/pull/2): support for CPU/GPU choice and initialization before starting the app.

I just released the package at https://pypi.org/project/open-text-embeddings/.

Kindly let's me know if you think there are ways to improve it. This is the first python package I publish to pypi.

**Closed as completed by limcheekin** 2023-09-27 09:55 UTC
